# Rust code formatting configurations
## https://github.com/rust-lang/rustfmt/blob/master/Configurations

# Basic
## Use spaces for indention
hard_tabs = false
## maximum line width
max_width = 80
## this option configures a set of other options:
##   - fn_call_width
##   - attr_fn_like_width
##   - struct_lit_width
##   - struct_variant_width
##   - array_width
##   - chain_width
##   - single_line_if_else_max_width
## "Max" means all the options in the set is set to `max_width
use_small_heuristics = "Max"

# Imports
## Controls how imports are structured in use statements
imports_granularity = "Crate"
## Reorder import and extern crate statements 
##  alphabetically in groups 
##  (a group is separated by a newline)
reorder_imports = true

# Consistency
## Unix or Windows line endings
newline_style = "Unix"

# Misc
## Maximum width of a chain to fit on one line.
chain_width = 80
## Put spaces around the .., ..=, and ... range operators
spaces_around_ranges = false
## Where to put a binary operator when a binary expression goes multiline.
binop_separator = "Back"
## Reorder impl items. type and const are put first, then macros and methods.
reorder_impl_items = false
## Controls whether to include a leading pipe on match arms
match_arm_leading_pipes = "Preserve"
## Controls whether arm bodies are wrapped 
##  in cases where the first line of the body cannot fit on the same line 
##  as the => operator.
match_arm_blocks = false
## Put a trailing comma after a block based match arm 
##  (non-block arms are not affected)
match_block_trailing_comma = true
## How to handle trailing commas for lists
trailing_comma = "Vertical"
## Add trailing semicolon after break, continue and return
trailing_semicolon = false
## Use field initialize shorthand if possible.
use_field_init_shorthand = true
## Skip formatting files and directories that match the specified pattern
ignore = [
    # "src/types.rs"
]
## Specifies which edition is used by the parser.
edition = "2021"
