// Chainbridge chain ID
pub const CHAINBRIDGE_ID_ETHEREUM: u8 = 0;
pub const CHAINBRIDGE_ID_KHALA: u8 = 1;
// pub const CHAINBRIDGE_ID_MOONRIVER: u8 = 2;
pub const CHAINBRIDGE_ID_PHALA: u8 = 3;
pub const ACALA_PARACHAIN_ID: u32 = 2000;
pub const MOONBEAM_PARACHAIN_ID: u32 = 2004;
pub const PHALA_PARACHAIN_ID: u32 = 2035;
pub const KHALA_PARACHAIN_ID: u32 = 2035;
pub const MOONRIVER_PARACHAIN_ID: u32 = 2023;
