name: Build and Test (Gramine)

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  cargo-tests:
    name: Run cargo tests
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "true"
      - uses: ./.github/actions/install_toolchain
      - name: Run cargo tests
        run: cargo test -vv --workspace --exclude node-executor --exclude phala-node

  cargo-clippy:
    name: Run cargo clippy
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "true"
      - uses: ./.github/actions/install_toolchain
      - name: Install clippy
        run: rustup component add clippy
      - name: Run cargo clippy
        run: cargo clippy --tests -- -D warnings && cd standalone/pruntime && cargo clippy --tests -- -D warnings

  cargo-fmt:
    name: Run cargo fmt
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "true"
      - uses: ./.github/actions/install_toolchain
      - name: Install rustfmt
        run: rustup component add rustfmt
      - name: Run cargo fmt
        run: cargo fmt --all -- --check
