name: Index cargo contract check

on:
  pull_request:
    branches:
      - "main"

env:
  CARGO_TERM_COLOR: always

jobs:
  cargo-contract-build:
    name: Run cargo contract build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "true"
      - uses: ./.github/actions/install_toolchain
      - name: Install cargo-contract
        run: rustup component add rust-src && cargo install cargo-dylint && cargo install dylint-link && cargo install cargo-contract --version ^1 --force
      - name: Install Binaryen
        run: "cd /tmp \
          && curl -OL https://github.com/WebAssembly/binaryen/releases/download/version_110/binaryen-version_110-x86_64-linux.tar.gz \
          && tar xf binaryen-version_110-x86_64-linux.tar.gz \
          && sudo cp binaryen-version_110/bin/* /bin/ \
          && sudo cp binaryen-version_110/include/* /usr/include \
          && sudo cp binaryen-version_110/lib/* /lib/ \
          && rm -rf binaryen-version_110"
      - name: Run cargo contract build for executor contracts
        run: cd contracts/index_executor && cargo contract build
