name: Index cargo contract check

on:
  pull_request:
    branches:
      - "main"

env:
  CARGO_TERM_COLOR: always

jobs:
  cargo-contract-check:
    name: Run cargo contract check
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "true"
      - uses: ./.github/actions/install_toolchain
      - name: Install cargo-contract
        run: rustup component add rust-src && cargo install cargo-dylint && cargo install dylint-link && cargo install --force --locked cargo-contract
      - name: Run cargo contract check for sample contracts
        run: cd contracts/semi-bridge && cargo contract check
